---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE | PascalCase
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .go: snake_case
  .json: kebab-case
  .rb: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case
  .toml: kebab-case
  .feature: kebab-case

  .java: PascalCase
  .kt: PascalCase
  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case
  .hbs: kebab-case
  .svg: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase

  .babelrc: lowercase
  .env: lowercase
  .dockerignore: lowercase
  .folderslintrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .shellcheckrc: lowercase

  helmcharts/*:
    Chart.yaml: PascalCase

ignore:
  - ansible/roles/ansible-roles-collection

  # commons
  - .ansible
  - .git
  - .idea
  - .task
  - .vagrant
  - .vscode
  - node_modules
  - target

  # linter definitions etc.
  - .ansible-lint.yml
  - .editorconfig
  - .kube-linter.yml
  - .ls-lint.yml
  - .lychee.toml
  - .markdownlint.yml
  - .pre-commit-config.yaml
  - .releaserc.js
  - .yamllint.yml
