---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  update:
    desc: Update project dependencies and submodules
    cmds:
      - git submodule update --remote

  cleanup:
    desc: Cleanup the environment
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - rm -rf .cache
      - rm -rf .vagrant
      - rm -rf node_modules
      - rm -rf target
      - sudo rm -rf .ansible
      - for: &helm-charts ['echoserver', 'monitoring']
        cmd: sudo rm -rf helmcharts/{{ .ITEM }}/charts/*
      - for: *helm-charts
        cmd: sudo rm -rf helmcharts/{{ .ITEM }}/Chart.lock
      - find . -type f -exec chmod +r {} +
      - find . -type d -exec chmod +r {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - task: update

  # ===============================================================================================

  lint:
    desc: Run all project linters outside of Dockerfile linters and helm linters
    cmds:
      - for: ['yaml', 'filenames', 'folders', 'ansible'] # , 'workflows', 'markdown-links', 'k8s-manifests']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
      - task: lint:helm

  lint:helm:
    desc: Run all Helm linters
    cmds:
      - for: *helm-charts
        cmd: docker compose up helm-{{ .ITEM }}-dependencies --exit-code-from helm-{{ .ITEM }}-dependencies
      - for: *helm-charts
        cmd: docker compose up helm-{{ .ITEM }}-lint --exit-code-from helm-{{ .ITEM }}-lint

  # ===============================================================================================

  vagrant:up:
    desc: Start Vagrantbox
    cmds:
      - vagrant validate
      - task: vagrant:halt
      - vagrant up
      - task: vagrant:ssh

  vagrant:halt:
    desc: Halt Vagrantbox
    cmds:
      - vagrant halt

  vagrant:ssh:
    desc: SSH into Vagrantbox
    cmds:
      - vagrant ssh

  vagrant:destroy:
    desc: Remove Vagrantbox and associated files
    cmds:
      - task: vagrant:halt
      - vagrant destroy -f
      - rm -rf .vagrant
