---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  sync:assets-from-github:
    desc: 'Sync assets from the central sommerfeldio/.github repository'
    cmds:
      - echo "Syncing assets from the central sommerfeldio/.github repository..."
      - task: common:download
        vars: { DEST: ".github/copilot-instructions.md", URL: "{{ .REPO }}/refs/heads/main/.github/copilot-instructions.md" }
      - task: common:download
        vars: { DEST: ".vscode/settings.json", URL: "{{ .REPO }}/refs/heads/main/.vscode/settings.json" }
      - task: common:download
        vars: { DEST: ".github/workflows/codeql.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/codeql.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-issues.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-issues.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-labels.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-labels.yml" }

  # ===============================================================================================

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - rm -rf .cache
      - rm -rf .vagrant
      - rm -rf node_modules
      - rm -rf target
      - sudo rm -rf .ansible
      - find . -type f -exec chmod +r {} +
      - find . -type d -exec chmod +r {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - git submodule update --remote

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'filenames', 'folders'] # , 'workflows', 'markdown-links'
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  vagrant:start:
    desc: Start Vagrantbox
    cmds:
      - vagrant validate
      - task: vagrant:stop
      - vagrant up
      - task: vagrant:ssh

  vagrant:stop:
    desc: Halt Vagrantbox
    cmds:
      - vagrant halt

  vagrant:ssh:
    desc: SSH into Vagrantbox
    cmds:
      - vagrant ssh

  vagrant:remove:
    desc: Remove Vagrantbox and associated files
    cmds:
      - vagrant destroy -f
      - rm -rf .vagrant
