{
 "title": "Alloy / Cluster Overview",
 "tags": [ "alloy" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cluster_node_info{job=~\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node table",
   "type": "table",
   "description": "Nodes info.\n",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "cluster_node_info{job=~\"$job\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Convergance state",
   "type": "stat",
   "description": "Whether the cluster state has converged.\n\nIt is normal for the cluster state to be diverged briefly as gossip events propagate. It is not normal for the cluster state to be diverged for a long period of time.\n\nThis will show one of the following:\n\n* Converged: Nodes are aware of all other nodes, with the correct states.\n* Not converged: A subset of nodes aren't aware of their peers, or don't have an updated view of peer states.\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp((\n  sum(stddev by (state) (cluster_node_peers{job=~\"$job\"}) != 0) or\n  (sum(abs(sum without (state) (cluster_node_peers{job=~\"$job\"})) - scalar(count(cluster_node_info{job=~\"$job\"})) != 0))\n  ),\n  1, 1\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Convergance state timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "ceil(clamp((\n  sum(stddev by (state) (cluster_node_peers{job=~\"$job\"})) or\n  (sum(abs(sum without (state) (cluster_node_peers{job=~\"$job\"})) - scalar(count(cluster_node_info{job=~\"$job\"}))))\n  ),\n  0, 1\n))\n",
     "legendFormat": "Converged"
    }
   ]
  },
  {
   "title": "Number of peers seen by each instance",
   "type": "timeseries",
   "description": "The number of cluster peers seen by each instance.\n\nWhen cluster is converged, every peer should see all the other instances. When we have a split brain or one\npeer not joining the cluster, we will see two or more groups of instances that report different peer numbers\nfor an extended period of time and not converging.\n\nThis graph helps to identify which instances may be in a split brain state.\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "sum by(instance) (cluster_node_peers{job=~\"$job\"})\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}