{
 "title": "Alloy / Cluster Node",
 "tags": [ "alloy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Info",
   "type": "table",
   "description": "Information about a specific cluster node.\n\n* Lamport clock time: The observed Lamport time on the specific node's clock used to provide partial ordering around gossip messages. Nodes should ideally be observing roughly the same time, meaning they are up-to-date on the cluster state. If a node is falling behind, it means that it has not recently processed the same number of messages and may have an outdated view of its peers.\n\n* Internal cluster state observers: The number of Observer functions that are registered to run whenever the node detects a cluster change.\n\n* Gossip health score: A health score assigned to this node by the memberlist implementation. The lower, the better.\n\n* Gossip protocol version: The protocol version used by nodes to communicate with one another. It should match across all nodes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(cluster_node_lamport_time{job=~\"$job\", instance=~\"$instance\"}) \n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_update_observers{job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_gossip_health_score{job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_gossip_proto_version{job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(cluster_node_gossip_received_events_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Known peers",
   "type": "stat",
   "description": "Known peers to the node (including the local node).\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:peers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_node_peers{job=~\"$job\", instance=~\"$instance\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers by state",
   "type": "timeseries",
   "description": "Known peers to the node by state (including the local node).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "targets": [
    {
     "expr": "cluster_node_peers{job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Gossip Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Transport bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cluster_transport_rx_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "rx"
    },
    {
     "expr": "-1 * rate(cluster_transport_tx_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packet write success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  rate(cluster_transport_tx_packets_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) /\n  rate(cluster_transport_tx_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n",
     "legendFormat": "Tx success %"
    },
    {
     "expr": "1 - (\n  rate(cluster_transport_rx_packets_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) /\n  rate(cluster_transport_rx_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n",
     "legendFormat": "Rx success %"
    }
   ]
  },
  {
   "title": "Pending packet queue",
   "type": "timeseries",
   "description": "The number of packets enqueued currently to be decoded or encoded and sent during communication with other nodes.\n\nThe incoming and outgoing packet queue should be as empty as possible; a growing queue means that Alloy cannot keep up with the number of messages required to have all nodes informed of cluster changes, and the nodes may not converge in a timely fashion.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "cluster_transport_tx_packet_queue_length{job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "tx queue"
    },
    {
     "expr": "cluster_transport_rx_packet_queue_length{job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "rx queue"
    }
   ]
  },
  {
   "title": "Stream bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cluster_transport_stream_rx_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "rx"
    },
    {
     "expr": "-1 * rate(cluster_transport_stream_tx_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Stream write success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  rate(cluster_transport_stream_tx_packets_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) /\n  rate(cluster_transport_stream_tx_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n",
     "legendFormat": "Tx success %"
    },
    {
     "expr": "1 - (\n  rate(cluster_transport_stream_rx_packets_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) /\n  rate(cluster_transport_stream_rx_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)\n",
     "legendFormat": "Rx success %"
    }
   ]
  },
  {
   "title": "Open transport streams",
   "type": "timeseries",
   "description": "The number of open connections from this node to its peers.\n\nEach node picks up a subset of its peers to continuously gossip messages around cluster status using streaming HTTP/2 connections. This panel can be used to detect networking failures that result in cluster communication being disrupted and convergence taking longer than expected or outright failing.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "cluster_transport_streams{job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "Open streams"
    }
   ]
  }
 ]
}